import streamlit as st
import json
import os
from datetime import datetime
from dotenv import load_dotenv
from openai import OpenAI

# -------------------------
# ENV + SECRETS (Cloud Safe)
# -------------------------
load_dotenv()

def get_secret(key, default=None):
    return os.getenv(key) or st.secrets.get(key, default)

api_key = get_secret("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

st.set_page_config(page_title="VSO Founder Console", layout="wide")

# -------------------------
# PASSWORD GATE (NEW)
# -------------------------
if "authenticated" not in st.session_state:
    pwd = st.text_input("Enter Access Code", type="password")
    correct_pwd = get_secret("APP_PASSWORD", "demo123")

    if pwd:
        if pwd == correct_pwd:
            st.session_state.authenticated = True
            st.rerun()
        else:
            st.error("Incorrect password")
            st.stop()
    else:
        st.stop()

# -------------------------
# SAFE JSON LOADER (NEW)
# -------------------------
def load_json_safe(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception as e:
        st.error(f"Error loading {path}: {e}")
        return {}

# -------------------------
# HELPERS (UNCHANGED CORE)
# -------------------------
def extract_structured_snapshot(text):
    snapshot = {}
    sections = [
        "Decision Frame",
        "Strategic Interpretation",
        "Critical Assumptions",
        "Second-Order Effect",
        "Blind Spots",
        "Recommended Posture",
        "Recommended Next Action"
    ]
    for section in sections:
        if section.lower() in text.lower():
            try:
                part = text.lower().split(section.lower())[1]
                snapshot[section] = part.strip()[:300]
            except:
                pass
    if not snapshot:
        first_sentence = text.split(".")[0][:120]
        snapshot["summary"] = first_sentence
    return snapshot


def auto_rename_thread(thread, latest_reply):
    if not thread["title"].startswith("Thread"):
        return
    first_line = latest_reply.split("\n")[0].strip()
    clean = first_line.replace("#", "").replace("*", "").strip()
    if len(clean) > 10:
        thread["title"] = clean[:60] + ("..." if len(clean) > 60 else "")


def compute_maturity(thread):
    msg_count = len(thread["messages"])
    if msg_count < 3:
        return "Exploratory"
    elif msg_count < 8:
        return "Directional"
    else:
        return "Decision-Ready"


def freshness_indicator(days):
    if days <= 7:
        return "🟢 Fresh"
    elif days <= 30:
        return "🟡 Aging"
    else:
        return "🔴 Stale"


def context_purity_label():
    return "🟡 Evidence + inference"


def export_board_memo(thread):
    return f"""
VSO STRATEGIC NOTE
==================

Thread: {thread['title']}
Maturity: {compute_maturity(thread)}
Generated: {datetime.now().strftime("%Y-%m-%d")}

Key Strategic Memory:
{json.dumps(thread['snapshot'], indent=2)}

---
Generated by VSO Founder Console
"""

# -------------------------
# LOAD CONTEXT FILES (SAFE)
# -------------------------
contextual_layer = load_json_safe("context/contextual_layer.json")
data_snapshot = load_json_safe("context/data_snapshot.json")
audit_snapshot = load_json_safe("context/audit_snapshot.json")

try:
    with open("prompts/advisory_prompt.txt") as f:
        advisory_prompt = f.read()
except:
    advisory_prompt = "Act as a board-grade strategy advisor."

# -------------------------
# AUDIT DATE SAFETY
# -------------------------
date_str = audit_snapshot.get("last_updated", "2026-01-01")
try:
    audit_date = datetime.strptime(date_str, "%Y-%m-%d")
except:
    audit_date = datetime(2026, 1, 1)
audit_age = (datetime.now() - audit_date).days

# -------------------------
# SESSION STATE
# -------------------------
if "threads" not in st.session_state:
    st.session_state.threads = {}

if "active_thread" not in st.session_state:
    st.session_state.threads["thread_1"] = {
        "title": "Thread 1",
        "messages": [],
        "snapshot": {}
    }
    st.session_state.active_thread = "thread_1"

active_thread = st.session_state.threads[st.session_state.active_thread]

# -------------------------
# HEADER
# -------------------------
st.title("🧠 VSO Founder Console")
st.caption("Founder-led strategic advisory powered by systematic reasoning")

# -------------------------
# SIDEBAR
# -------------------------
st.sidebar.markdown("### 🧬 Intelligence Stack")
st.sidebar.write("Context Layer: Loaded")
st.sidebar.write("Data Snapshot: Loaded")
st.sidebar.write(f"Audit Freshness: {freshness_indicator(audit_age)}")
st.sidebar.write("Mode: Advisory")

st.sidebar.markdown("---")
st.sidebar.markdown("### 🧠 Strategic Memory")
st.sidebar.write(f"Maturity: {compute_maturity(active_thread)}")
if active_thread["snapshot"]:
    st.sidebar.json(active_thread["snapshot"])
else:
    st.sidebar.caption("No memory yet — ask your first strategic question.")

# -------------------------
# THREADS
# -------------------------
st.sidebar.markdown("---")
st.sidebar.markdown("### 🧵 Strategic Threads")

thread_ids = list(st.session_state.threads.keys())
selected = st.sidebar.radio(
    "Active Thread",
    thread_ids,
    format_func=lambda x: st.session_state.threads[x]["title"]
)
st.session_state.active_thread = selected
active_thread = st.session_state.threads[selected]

if st.sidebar.button("➕ New Thread"):
    new_id = f"thread_{len(thread_ids)+1}"
    st.session_state.threads[new_id] = {
        "title": f"Thread {len(thread_ids)+1}",
        "messages": [],
        "snapshot": {}
    }
    st.session_state.active_thread = new_id
    st.rerun()

# -------------------------
# CHAT HISTORY
# -------------------------
for msg in active_thread["messages"]:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# -------------------------
# CHAT INPUT
# -------------------------
if prompt := st.chat_input("Ask your toughest strategic question…"):
    active_thread["messages"].append({"role": "user", "content": prompt})

    snapshot_memory = json.dumps(active_thread["snapshot"], indent=2)
    recent_messages = active_thread["messages"][-6:]
    conversation_memory = "\n".join(
        [f"{m['role'].upper()}: {m['content']}" for m in recent_messages]
    )

    full_context = f"""
SYSTEM CONTEXT
Contextual Layer:
{json.dumps(contextual_layer, indent=2)}

Data Snapshot:
{json.dumps(data_snapshot, indent=2)}

Audit Snapshot:
{json.dumps(audit_snapshot, indent=2)}

THREAD MEMORY:
{snapshot_memory}

RECENT DISCUSSION:
{conversation_memory}

Instructions:
{advisory_prompt}

CEO Question:
{prompt}
"""

    with st.chat_message("assistant"):
        with st.spinner("Analyzing with VSO reasoning engine..."):
            try:
                response = client.chat.completions.create(
                    model="gpt-5-mini",  # upgraded model
                    messages=[{"role": "user", "content": full_context}]
                )
                reply = response.choices[0].message.content
            except Exception as e:
                reply = f"Model error: {str(e)}"

            st.markdown(reply)
            st.caption(f"Context Purity: {context_purity_label()}")

    active_thread["messages"].append({"role": "assistant", "content": reply})
    structured = extract_structured_snapshot(reply)
    active_thread["snapshot"] = structured
    auto_rename_thread(active_thread, reply)

# -------------------------
# EXPORT
# -------------------------
st.sidebar.markdown("---")
if st.sidebar.button("📤 Export Strategic Note"):
    report = export_board_memo(active_thread)
    st.sidebar.download_button(
        label="Download Board Note",
        data=report,
        file_name="vso_board_note.txt",
        mime="text/plain"
    )